import "./globals.css";

import { Poppins } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";

import type { Metadata } from "next";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${poppins.variable} antialiased`}>
      <body>
        {children}

        <Analytics />
      </body>
    </html>
  );
}
